apiVersion: v1
kind: Service
metadata:
  name: currency
spec:
  type: ClusterIP
  selector:
    app: currency
  ports:
    - port: 5000
      targetPort: 8080
      name: currency
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency
  template:
    metadata:
      labels:
        app: currency
    spec:
      containers:
        - name: currency
          image: currency
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: 500m
          ports:
            - containerPort: 8080
              name: http
